base: test.loc/
baseVariants:
  -
    base: test.loc/
    condition: 'applicationContext == "Development/Local"'
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=21'
languages:
  -
    title: Eng
    enabled: true
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: ab
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: global
    languageId: '0'
rootPageId: 1
routes: {  }
